### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by charleslparker** [lisa-lab/DeepLearningTutorials#104]
Is this code released under a license?  It would be good to have a license file in the root of the project, or have the license (or lack thereof) mentioned in the readme.

**Comment by nouiz** [comment]
I already did a PR for that earlier this morning:

https://github.com/lisa-lab/DeepLearningTutorials/pull/103

**Comment by charleslparker** [comment]
Fixing issues before they are submitted!  Clearly you are psychic.

Or maybe you've just trained a really good model.
