### ISSUE TITLE
Download links do not work for ATIS dataset

### ISSUE THREAD

**Issue by lxc-xx** [lisa-lab/DeepLearningTutorials#118]
Just found the links in the download.sh for ATIS do not work.
$DL_CMD http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold0.pkl.gz
$DL_CMD http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold1.pkl.gz
$DL_CMD http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold2.pkl.gz
$DL_CMD http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold3.pkl.gz
$DL_CMD http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold4.pkl.gz

It reported 403 error.

**Comment by nouiz** [comment]
I'm working to bring it back. It won't be super fast for administrative
reason.

**Comment by nouiz** [comment]
Update this repo. I fixed the url to new one that work.

thanks.
