### ISSUE TITLE
checking uidx == 0 in lstm.py

### ISSUE THREAD

**Issue by vshallc** [lisa-lab/DeepLearningTutorials#122]
uidx is initialised to 0 on line 544
then increased by 1 on line 555
so I think uidx == 0 on line 598 should be replaced by uidx == 1

**Comment by nouiz** [comment]
You are right that this comparison is useless. To be more clean, I compared best_p to None.

https://github.com/lisa-lab/DeepLearningTutorials/pull/123

thanks
