### ISSUE TITLE
Using theano.In breaks SdA

### ISSUE THREAD

**Issue by benjaminirving** [lisa-lab/DeepLearningTutorials#139]
Hi, 

Commit b701733044d73681b breaks SdA.py and the tests with error:

*Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SdA.py", line 382, in test_SdA
    batch_size=batch_size)
  File "SdA.py", line 226, in pretraining_functions
    self.x: train_set_x[batch_begin: batch_end]
  File "/local/lib/python2.7/site-packages/theano/compile/function.py", line 248, in function
    "In() instances and tuple inputs trigger the old "
NotImplementedError: In() instances and tuple inputs trigger the old semantics, which disallow using updates and givens*

Perhaps consider making these optional function arguments mandatory by removing theano.In

I can submit a pull request if it helps. 

Thanks.

**Comment by amit4111989** [comment]
Hey you are using the old version of Theano. I literally posted the same issue yesterday
They asked me to get the development version of theano
just clone this git://github.com/Theano/Theano.git
and run python setup. It automatically updated the theano version for me. I changed back to In() from Param() and it works now

**Comment by benjaminirving** [comment]
Thanks. Good to know. I didn't notice an older comment.

**Comment by amit4111989** [comment]
btw have you looked at the DA code? I had a specific doubt about the corruption process 
I think the corruption is suppose to happen to the first layer only. I may be wrong but the literature I read a while ago agrees with me

**Comment by benjaminirving** [comment]
Will take a look :)

**Comment by benjaminirving** [comment]
@amit4111989 My understanding is the training using denoising autoencoders happens at every level during training. But when training the n layer, the input of layer n (the output from layer n-1 must be uncorrupted). 
see [paper](http://delivery.acm.org/10.1145/1960000/1953039/11-3371-vincent.pdf)

I think this does happen in the code. 

btw, do you experience similar issues as this #140

**Comment by nouiz** [comment]
I make a PR to make DLT work again with Theano 0.7. We need to wait for the
next release before doing this Param -> In Change.

https://github.com/lisa-lab/DeepLearningTutorials/pull/141

thanks for the report.
