### ISSUE TITLE
results of rnnslu.py not as expected

### ISSUE THREAD

**Issue by wendysalonika** [lisa-lab/DeepLearningTutorials#144]
Hi,
I'm running your code rnnslu.py for ATIS (the the 5 folds of data you provide us with)
(DeepLearningTutorials/code/rnnslu.py)

I expected to get F1=94.98% as mentioned in the paper:
'Using Recurrent Neural Networks for Slot Filling in Spoken Language Understanding'
(table 3: Elman/Single,context(9))

Instead, the best performance with this code is F1=94.058% for cont_win=9 and emb_dim=100.
Is that what I'm suppose to get?

Thank you in advance!

**Comment by nouiz** [comment]
I supose you found your answer.
