### ISSUE TITLE
Need help to get started

### ISSUE THREAD

**Issue by isalirezag** [lisa-lab/DeepLearningTutorials#148]
I am very new to this topics and deep learning.
I have questions that may sound stupid but I need to ask them because I have noone to ask and I could not find them in google! :)
So I am using Ubuntu 14.04 and installed anaconda and python 2.7 and  installed Theano and make it work fine!

So here is my first question, do I need to install something else in order to use this DeepLearningTutorials? (if yes please tell me how).
Do I need to add any more PATH ? (hmmm if yes how :/ )

e.g. I was trying to do this tutorial regarding SdA (http://deeplearning.net/tutorial/code/SdA.py).
I could run this commands fine 
`import os
`
`import sys
`
`import timeit
`
`import numpy
`
`import theano
`
`import theano.tensor as T
`
`from theano.tensor.shared_randomstreams import RandomStreams.
`
However the next commands are not fine anymore, when I am trying to:
`from logistic_sgd import LogisticRegression, load_data
`
`from mlp import HiddenLayer
`
`from dA import dA`

I face the errors that no module to import....
 cannot import `LogisticRegression` or etc anymore.

Can anyone please tell me what I need to do to be able use the tutorials?
Thanks in advance.

**Comment by lamblin** [comment]
You can either download the missing files from http://deeplearning.net/tutorial/code/, or clone this GitHub repository and go inside `DeepLearningTutorials/code/`.

**Comment by isalirezag** [comment]
@lamblin I did
`export PATH=$HOME/DeepLearningTutorials/code:$PATH
`
but still not working.

**Comment by lamblin** [comment]
Can you report the exact full procedure you followed, and the full error message?

**Comment by lamblin** [comment]
Also, I did not say to add `DeepLearningTutorials/code` to the `PATH`, when I said "go inside", I mean `cd $HOME/DeepLearningTutorials/code` before launching `python`. Does that work?

**Comment by isalirezag** [comment]
@lamblin So im in my ipython and try to do the steps here (http://deeplearning.net/tutorial/code/SdA.py).

I did:
`import os
`
`import sys
`
`
import timeit
`
`import numpy
`
`import theano
`
`import theano.tensor as T
`
`from theano.tensor.shared_randomstreams import RandomStreams
`

so far so good.
when I did 
`from logistic_sgd import LogisticRegression, load_data`
The error showed up.

I did download the DeepLearningTutorials
and then did
`git clone https://github.com/lisa-lab/DeepLearningTutorials.git
`.
but still received the error that :

`ImportError: No module named logistic_sgd
`
hmmm I did not exactly get it, What  do you mean  `cd $HOME/DeepLearningTutorials/code` before launching python?

**Comment by lamblin** [comment]
I mean:
- exit `ipython`
- in a terminal, change the current directory by calling `cd $HOME/DeepLearningTutorials/code` if `$HOME` is indeed where you called `git clone ...`
- in that same terminal, relaunch `ipython`

**Comment by isalirezag** [comment]
@lamblin Thank you very much!!!
