### ISSUE TITLE
Using SdA

### ISSUE THREAD

**Issue by djsaunde** [lisa-lab/DeepLearningTutorials#156]
Hello,

Sorry to have to post this question here. I am attempting to build an SdA with an input size of 2880 neurons, where each of the input values are in the range [0, 1]. But, when training, even for large hidden layer sizes (~3000 x 3), the pre-training cost for the first layer never falls below ~180. Should this cost be below 100? Is there something I am missing?

**Comment by nouiz** [comment]
You can't have any specific number expectation for the preprocessing. The
only thing you can tell is that it should go down.
