### ISSUE TITLE
Question about dA / SdA

### ISSUE THREAD

**Issue by djsaunde** [lisa-lab/DeepLearningTutorials#158]
I would like to retrieve the encoding of the input vector from the autoencoder architecture. I am able to train an autoencoder, but would like to obtain the lower-dimensional encodings given by the hidden layers. Is there a way to do this?

**Comment by amarczew** [comment]
#159 look the thread...

**Comment by nouiz** [comment]
I think the answer is in gh-159, so I'll close this issue.
