### ISSUE TITLE
Convolutional Neural Networks Tutorial code (code/convolutional_mlp.py) raises error

### ISSUE THREAD

**Issue by arthurlaurens** [lisa-lab/DeepLearningTutorials#165]
Trying to run the code belonging to the tutorial: http://deeplearning.net/tutorial/lenet.html raises the following error:
~~~~
Downloading data from http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz
... loading data
... building the model
Traceback (most recent call last):
  File "code/convolutional_mlp.py", line 345, in <module>
    evaluate_lenet5()
  File "code/convolutional_mlp.py", line 182, in evaluate_lenet5
    poolsize=(2, 2)
  File "code/convolutional_mlp.py", line 97, in __init__
    input_shape=image_shape
  File "/home/arthur/.local/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 149, in conv2d
    imshp=imshp, kshp=kshp, nkern=nkern, bsize=bsize, **kargs)
TypeError: __init__() got an unexpected keyword argument 'input_shape'
~~~~

All I did was cloning this repo and running the following command:
python code/convolutional_mlp.py

As i was not able to find any information about this on the web I thought I might post it here.

**Comment by costapt** [comment]
Are you sure you have the latest theano version? It seems like your code is passing through the old deprecated version of conv2d (see https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv.py).

Either way, I think you can delete the "input_shape=image_shape" (line 97) from the convolutional_mlp.py file. The argument is used for optimization purposes and is not mandatory at compile time (http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.conv2d)

**Comment by nouiz** [comment]
I also think you have a too old Theano. Update to Theano 0.8.2 or the dev version. I'll close this issue as I'm pretty sure of the answer, but if it don't fix it, tell us.

**Comment by tdlshashi** [comment]
Change the variable name "input_shape"  to "image_shape"  in line 97.
