### ISSUE TITLE
convulational_mlp.py -  python.exe has stopped working 

### ISSUE THREAD

**Issue by tdlshashi** [lisa-lab/DeepLearningTutorials#171]
I am using Windows 7 32 bit. When I run the convulational_mlp.py,  Python crashes with exit code - 1073741819 (0xC0000005).

It crashes just after 
.... training

**Comment by nouiz** [comment]
Do you have this problem with the other examples? Which blas Didi you use?
Can you try with this Theano flag

blas.ldflags=

This could trigger a different implementation.

Make sure to use Theano development version.

Le 28 sept. 2016 02:28, "Shashikant Ghangare" <notifications@github.com> a
écrit :

**Comment by tdlshashi** [comment]
Today I ran it on Ubuntu,  it ran successfully...  I think I used old version of Theano on Windows..

**Comment by nouiz** [comment]
ok. thanks for the update.
