### ISSUE TITLE
In mlp.py, why are the parameters of the two models added together?

### ISSUE THREAD

**Issue by Valentin4869** [lisa-lab/DeepLearningTutorials#183]
In [mlp.py](https://github.com/lisa-lab/DeepLearningTutorials/blob/master/code/mlp.py#L194)  at line 194, the paramters of the hidden layer and the output layer are added together. Is this a typo? If not, then why are we adding the parameters?

**Comment by nouiz** [comment]
This is not what you think it is. What we add are 2 lists of parameters. We
don't add the parameters togethers, we just create a liste that have all
the parameters together. We use that list of all the parameter later for
the gradient computation.
