### ISSUE TITLE
TheanoConfigParser object has no attribute 'scan' when I run lstm.py

### ISSUE THREAD

**Issue by tankle** [lisa-lab/DeepLearningTutorials#70]
I run the command: python lstm.py

then throw follow error, what's the problem ?

Traceback (most recent call last):
  File "lstm.py", line 577, in <module>
    theano.config.scan.allow_gc = False
AttributeError: 'TheanoConfigParser' object has no attribute 'scan'

**Comment by nouiz** [comment]
Update Theano do the development version: 

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

This will fix this problem. Otherwise, you can just comment that line. It will just be slower, but it will work correctly.
