### ISSUE TITLE
DBN tutorial code needs to be updated

### ISSUE THREAD

**Issue by rfeinman** [lisa-lab/DeepLearningTutorials#74]
While training the tutorial DBN model on MNIST data, I noticed that each pre-training epoch was taking about 7 seconds to complete, as compared to other DBN architectures which took around 0.5 seconds per epoch. After profiling a few of the compiled theano functions and doing some research online, I discovered that the issue is exactly what is described in this ticket: https://github.com/Theano/Theano/issues/1233. 
The tutorial code should be updated so that those who are trying out theano for the first time by running the tutorial models are not turned away by this excessive training time cost. A simple fix would be to update lines 11 and 61 in DBN.py to the following:

[11]:  import theano.sandbox.rng_mrg import MRG_RandomStreams 
[61]:  theano_rng = MRG_RandomStreams(numpy_rng.randint(2 ** 30))

-R. Feinman

**Comment by nouiz** [comment]
Put a comment that tell why we use this one too. thanks for the suggestion.
