### ISSUE TITLE
Saving the Model and Predicting

### ISSUE THREAD

**Issue by varghesealex90** [lisa-lab/DeepLearningTutorials#77]
Hi;
Is it possible to save the network after every say 100 training samples.
Once the training is completed, is it possible to load the network from the HDD and use for predicting on a new dataset?
Regards
Varghese

**Comment by Lancelod-Liu** [comment]
Of course, you could pickle the instance of the model and use *instance.W.get_value(True)* to get the params.

**Comment by varghesealex90** [comment]
Thank you for the response. How about using the the trained network to
predict

**Comment by Lancelod-Liu** [comment]
I've tried code like 
```
predictor = theano.function(inputs = [x], outputs = classifier.y_pred)
```
where *classifier* is defined as:
```
classifier = LogisticRegression(input=x, n_in=24 * 48, n_out=32)
```

**Comment by varghesealex90** [comment]
Thank you
Regards
Varghese

**Comment by nouiz** [comment]
It seem that this issue is solved, so I'll close this issue.
