### ISSUE TITLE
Bias term be added twice in lstm.py

### ISSUE THREAD

**Issue by wps712** [lisa-lab/DeepLearningTutorials#81]
It seems that the bias term in lstm_layer is added twice.  Is that a mistake ?

The bias is first added here:
state_below = (tensor.dot(state_below, tparams[_p(prefix, 'W')]) +
                   tparams[_p(prefix, 'b')])

and then in the _step function:
 def _step(m_, x_, h_, c_):
        preact = tensor.dot(h_, tparams[_p(prefix, 'U')])
        preact += x_
        preact += tparams[_p(prefix, 'b')]
        ......

**Comment by nouiz** [comment]
This have been fixed by gh-85.

thanks for the report.

This shouldn't change the results, but could change the scale of the weights.
