### ISSUE TITLE
"Duplicate name" warning while dumping a SdA

### ISSUE THREAD

**Issue by DelightRun** [lisa-lab/DeepLearningTutorials#95]
There will be `User Warning: Duplicate name W` and `User Warning: Duplicate name b` while I dumping my SdA model using `theano.misc.pkl_utils.dump`. And I found that a `SdA` model cannot be loaded correctly because of the duplicate name of variables `W` and `b`.

So is it necessary to use different name for each theano tensor `W` and `b` in model classes? In fact, that's the way I solve the problem mentioned above.

**Comment by nouiz** [comment]
The name is just for the user, so normally, having duplicate name isn't a problem. Can you give me the full stack trace? I'm not able to find it in Theano.

**Comment by DelightRun** [comment]
This is the warning.

![qq20150629-3 2x](https://cloud.githubusercontent.com/assets/4102875/8411344/1bdf4dd8-1eb6-11e5-9f94-4253da62b720.jpg)

And I found that theano can't restore SdA model correctly, it will mix up the `W` and `b` parameters between the Hidden Layer and Softmax Layer

**Comment by nouiz** [comment]
Update Theano to the development version.. I think it is now fixed.

**Comment by DelightRun** [comment]
OK，thanks.

> 在 2015年6月29日，23:41，Frédéric Bastien <notifications@github.com> 写道：
> 
> Update Theano to the development version.. I think it is now fixed.
>

**Comment by DelightRun** [comment]
BTW, how to upgrade Theano to the development version via `pip`?

**Comment by nouiz** [comment]
see this page: http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by DelightRun** [comment]
Thanks you.

Frédéric Bastien wrote:
